"""Auto-generated IK-related CAD transforms.

Generated by `scripts/rs_export_joint_tool0_tf.py`. Re-run that exporter after
the CAD male-joint OCF or tool0 frame changes.

All translations are stored in millimeters.

`MALE_JOINT_OCF_TO_TOOL0[joint_type][arm_side]` is a 4x4 that takes the
male-joint local frame (OCF) to the corresponding arm's tool0 frame:

    tool0_world = male_ocf_world @ MALE_JOINT_OCF_TO_TOOL0[joint_type][arm_side]

`arm_side` is "left" or "right" (the two Husky arms carry different
physical tools, so the transform differs per side).
"""

MALE_JOINT_OCF_TO_TOOL0 = {
    "T20_Male": {
        "left": (
            (1, -1.25311976e-13, -2.78248481e-29, -70),
            (1.25311976e-13, 1, 5.77315973e-15, -1.04325308e-11),
            (-6.95621203e-28, -5.77315973e-15, 1, -80),
            (0, 0, 0, 1),
        ),
        "right": (
            (1, -1.25311976e-13, 1.4443907e-12, 70),
            (1.25311976e-13, 1, 5.99520433e-15, 7.11114575e-12),
            (-1.4443907e-12, -5.99520433e-15, 1, -80),
            (0, 0, 0, 1),
        ),
    },
}
