"""Auto-generated IK-related CAD transforms.

Generated by `scripts/rs_define_robotic_tool.py` (SupportGripper mode).
Re-run that mode after the CAD bar-grasp frame or tool0 frame changes.

All translations are stored in millimeters.

`BAR_GRASP_TO_TOOL0[gripper_kind]` is a 4x4 that takes the bar-grasp
frame (origin on bar centerline, Z along bar) to the gripper's tool0
frame:

    tool0_world = bar_grasp_world @ BAR_GRASP_TO_TOOL0[gripper_kind]

(The male-joint OCF -> tool0 transform used to live here too; it now
comes from `M_tcp_from_block` in `scripts/core/robotic_tools.json`,
written by RSDefineRoboticTool's AssemblyTool mode.)
"""

BAR_GRASP_TO_TOOL0 = {
    "Robotiq": (
        (-1, 0, 0, 3.91769069e-09),
        (0, 0, 1, -166.130956),
        (0, 1, 0, 8.75607142e-10),
        (0, 0, 0, 1),
    ),
}
