#! python 3
# venv: scaffolding_env
# r: numpy==1.24.4
# r: scipy==1.13.1
"""RSExportGraspTool0TF - Export grasp/joint -> tool0 transforms for IK.

Two modes, selected via a top-level prompt:

* **Joint** mode: pick a baked male-joint frame group and a baked tool0
  frame group; computes ``inverse(male_ocf) @ tool0`` and merges into
  ``MALE_JOINT_OCF_TO_TOOL0[joint_type][arm_side]``.

* **Gripper** mode: pick a baked bar-grasp frame group (origin on the
  bar centerline, Z along the bar) and a baked tool0 frame group;
  computes ``inverse(bar_grasp) @ tool0`` and merges into
  ``BAR_GRASP_TO_TOOL0[gripper_kind]``.

Both dicts are written to ``scripts/core/config_generated_ik.py``. The
writer preserves the *other* dict on partial re-runs, so running gripper
mode does not erase joint entries (and vice versa).

The two UR arms on the dual-arm Husky carry different physical tools, so
the joint-mode transform differs per arm side. Run joint mode twice per
joint type (once for "left", once for "right") before using RSIKKeyframe.
"""

from __future__ import annotations

import importlib
import os
import sys

import numpy as np
import rhinoscriptsyntax as rs


SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
if SCRIPT_DIR not in sys.path:
    sys.path.insert(0, SCRIPT_DIR)

from core import config_generated_ik as _generated_ik
from core.rhino_frame_io import (
    doc_unit_scale_to_mm,
    reconstruct_frame,
    resolve_frame_group,
)
from core.transforms import invert_transform


DEFAULT_JOINT_TYPE = "T20_Male"
DEFAULT_GRIPPER_KIND = "Robotiq"
ARM_SIDES = ("left", "right")


def _format_male_dict(entries: dict) -> str:
    if not entries:
        return "MALE_JOINT_OCF_TO_TOOL0 = {}\n"
    lines = ["MALE_JOINT_OCF_TO_TOOL0 = {"]
    for joint_type in sorted(entries.keys()):
        per_side = entries[joint_type]
        lines.append(f'    "{joint_type}": {{')
        for side in ARM_SIDES:
            if side not in per_side:
                continue
            lines.append(f'        "{side}": (')
            for row in np.asarray(per_side[side], dtype=float):
                lines.append(
                    "            (" + ", ".join(f"{float(v):.9g}" for v in row) + "),"
                )
            lines.append("        ),")
        lines.append("    },")
    lines.append("}\n")
    return "\n".join(lines)


def _format_gripper_dict(entries: dict) -> str:
    if not entries:
        return "BAR_GRASP_TO_TOOL0 = {}\n"
    lines = ["BAR_GRASP_TO_TOOL0 = {"]
    for kind in sorted(entries.keys()):
        lines.append(f'    "{kind}": (')
        for row in np.asarray(entries[kind], dtype=float):
            lines.append(
                "        (" + ", ".join(f"{float(v):.9g}" for v in row) + "),"
            )
        lines.append("    ),")
    lines.append("}\n")
    return "\n".join(lines)


def _write_generated_ik(path: str, male_entries: dict, gripper_entries: dict) -> None:
    header = (
        '"""Auto-generated IK-related CAD transforms.\n\n'
        "Generated by `scripts/rs_export_grasp_tool0_tf.py`. Re-run that exporter\n"
        "after the CAD male-joint OCF, bar-grasp frame, or tool0 frame changes.\n\n"
        "All translations are stored in millimeters.\n\n"
        "`MALE_JOINT_OCF_TO_TOOL0[joint_type][arm_side]` is a 4x4 that takes the\n"
        "male-joint local frame (OCF) to the corresponding arm's tool0 frame:\n\n"
        "    tool0_world = male_ocf_world @ MALE_JOINT_OCF_TO_TOOL0[joint_type][arm_side]\n\n"
        "`arm_side` is \"left\" or \"right\" (the two Husky arms carry different\n"
        "physical tools, so the transform differs per side).\n\n"
        "`BAR_GRASP_TO_TOOL0[gripper_kind]` is a 4x4 that takes the bar-grasp\n"
        "frame (origin on bar centerline, Z along bar) to the gripper's tool0\n"
        "frame:\n\n"
        "    tool0_world = bar_grasp_world @ BAR_GRASP_TO_TOOL0[gripper_kind]\n"
        '"""\n\n'
    )
    body = _format_male_dict(male_entries) + "\n\n" + _format_gripper_dict(gripper_entries)
    with open(path, "w", encoding="utf-8") as stream:
        stream.write(header + body)


def _load_existing_male(module) -> dict:
    raw = getattr(module, "MALE_JOINT_OCF_TO_TOOL0", {}) or {}
    existing: dict = {}
    for key, value in raw.items():
        if not isinstance(value, dict):
            raise RuntimeError(
                f"config_generated_ik.py entry '{key}' uses the legacy flat schema "
                "(single matrix per joint_type). Delete it and re-run "
                "RSExportGraspTool0TF in Joint mode for both left and right arms."
            )
        existing[str(key)] = {
            str(s): np.asarray(v, dtype=float) for s, v in value.items()
        }
    return existing


def _load_existing_gripper(module) -> dict:
    raw = getattr(module, "BAR_GRASP_TO_TOOL0", {}) or {}
    return {str(k): np.asarray(v, dtype=float) for k, v in raw.items()}


def _prompt_mode() -> str | None:
    value = rs.GetString("Export mode", "Joint", ["Joint", "Gripper"])
    if value is None:
        return None
    v = value.strip().lower()
    if v.startswith("j"):
        return "joint"
    if v.startswith("g"):
        return "gripper"
    return None


def _prompt_joint_type() -> str | None:
    value = rs.GetString("Joint type key", DEFAULT_JOINT_TYPE)
    if value is None:
        return None
    value = value.strip()
    if not value:
        return None
    return value


def _prompt_arm_side() -> str | None:
    value = rs.GetString("Arm side", "left", list(ARM_SIDES))
    if value is None:
        return None
    value = value.strip().lower()
    if value not in ARM_SIDES:
        rs.MessageBox(
            f"Arm side must be one of {ARM_SIDES}.", 0, "Export Grasp -> tool0 TF"
        )
        return None
    return value


def _prompt_gripper_kind() -> str | None:
    value = rs.GetString("Gripper kind", DEFAULT_GRIPPER_KIND)
    if value is None:
        return None
    value = value.strip()
    if not value:
        return None
    return value


def _run_joint_mode(output_path: str, scale_to_mm: float) -> None:
    joint_type = _prompt_joint_type()
    if joint_type is None:
        print("RSExportGraspTool0TF: Cancelled.")
        return

    arm_side = _prompt_arm_side()
    if arm_side is None:
        print("RSExportGraspTool0TF: Cancelled.")
        return

    male_group = resolve_frame_group(
        f"Select the baked male-joint frame group for {joint_type} / {arm_side} arm"
    )
    if male_group is None:
        print("RSExportGraspTool0TF: Cancelled.")
        return

    tool0_group = resolve_frame_group(
        f"Select the baked tool0 frame group for {joint_type} / {arm_side} arm"
    )
    if tool0_group is None:
        print("RSExportGraspTool0TF: Cancelled.")
        return

    try:
        male_frame, male_label = reconstruct_frame(male_group[1], scale_to_mm)
        tool0_frame, tool0_label = reconstruct_frame(tool0_group[1], scale_to_mm)
    except ValueError as exc:
        rs.MessageBox(str(exc), 0, "Export Grasp -> tool0 TF")
        return

    tf = invert_transform(male_frame) @ tool0_frame

    male_entries = _load_existing_male(_generated_ik)
    gripper_entries = _load_existing_gripper(_generated_ik)
    male_entries.setdefault(joint_type, {})[arm_side] = tf

    _write_generated_ik(output_path, male_entries, gripper_entries)

    translation = tf[:3, 3]
    print(f"RSExportGraspTool0TF[Joint]: '{joint_type}' / '{arm_side}' written to {output_path}")
    print(
        f"  male group='{male_label}', tool0 group='{tool0_label}', "
        f"translation (mm) = [{translation[0]:.3f}, {translation[1]:.3f}, {translation[2]:.3f}]"
    )
    missing_sides = [s for s in ARM_SIDES if s not in male_entries.get(joint_type, {})]
    if missing_sides:
        print(
            f"  Note: '{joint_type}' still missing arm side(s): {missing_sides}. "
            "Re-run this script for the missing arm(s) before using RSIKKeyframe."
        )


def _run_gripper_mode(output_path: str, scale_to_mm: float) -> None:
    gripper_kind = _prompt_gripper_kind()
    if gripper_kind is None:
        print("RSExportGraspTool0TF: Cancelled.")
        return

    grasp_group = resolve_frame_group(
        "Select the baked BAR-GRASP frame group (origin on bar centerline, Z along bar)"
    )
    if grasp_group is None:
        print("RSExportGraspTool0TF: Cancelled.")
        return

    tool0_group = resolve_frame_group(
        "Select the baked tool0 frame group"
    )
    if tool0_group is None:
        print("RSExportGraspTool0TF: Cancelled.")
        return

    try:
        grasp_frame, grasp_label = reconstruct_frame(grasp_group[1], scale_to_mm)
        tool0_frame, tool0_label = reconstruct_frame(tool0_group[1], scale_to_mm)
    except ValueError as exc:
        rs.MessageBox(str(exc), 0, "Export Grasp -> tool0 TF")
        return

    tf = invert_transform(grasp_frame) @ tool0_frame

    male_entries = _load_existing_male(_generated_ik)
    gripper_entries = _load_existing_gripper(_generated_ik)
    gripper_entries[gripper_kind] = tf

    _write_generated_ik(output_path, male_entries, gripper_entries)

    translation = tf[:3, 3]
    print(f"RSExportGraspTool0TF[Gripper]: '{gripper_kind}' written to {output_path}")
    print(
        f"  bar_grasp group='{grasp_label}', tool0 group='{tool0_label}', "
        f"translation (mm) = [{translation[0]:.3f}, {translation[1]:.3f}, {translation[2]:.3f}]"
    )


def main() -> None:
    importlib.reload(_generated_ik)

    mode = _prompt_mode()
    if mode is None:
        print("RSExportGraspTool0TF: Cancelled.")
        return

    scale_to_mm = doc_unit_scale_to_mm()
    output_path = os.path.join(SCRIPT_DIR, "core", "config_generated_ik.py")

    if mode == "joint":
        _run_joint_mode(output_path, scale_to_mm)
    else:
        _run_gripper_mode(output_path, scale_to_mm)


if __name__ == "__main__":
    main()
