#! python 3
# venv: scaffolding_env
# r: numpy==1.24.4
# r: scipy==1.13.1
"""RSExportJointTool0TF - Export the male-joint OCF -> tool0 transform.

Prompts for (joint_type, arm_side), then picks a baked male-joint frame
group and a baked tool0 frame group. Computes

    tf = inverse(male_ocf) @ tool0_frame

such that `tool0_world = male_ocf_world @ tf`, and merges it into the
nested dict `MALE_JOINT_OCF_TO_TOOL0[joint_type][arm_side]` inside
`scripts/core/config_generated_ik.py`.

The two UR arms on the Husky carry different physical tools, so the
OCF -> tool0 transform differs per arm side. Run this script twice per
joint type (once for "left", once for "right") before using RSIKKeyframe.

Existing entries (other joint types, or the other arm side of the same
joint type) are preserved. Re-running for the same (joint_type, side)
overwrites the prior entry.
"""

from __future__ import annotations

import importlib
import os
import sys

import numpy as np
import rhinoscriptsyntax as rs


SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
if SCRIPT_DIR not in sys.path:
    sys.path.insert(0, SCRIPT_DIR)

from core import config_generated_ik as _generated_ik
from core.rhino_frame_io import (
    doc_unit_scale_to_mm,
    reconstruct_frame,
    resolve_frame_group,
)
from core.transforms import invert_transform


DEFAULT_JOINT_TYPE = "T20_Male"
ARM_SIDES = ("left", "right")


def _write_generated_ik(path: str, entries: dict) -> None:
    header = (
        '"""Auto-generated IK-related CAD transforms.\n\n'
        "Generated by `scripts/rs_export_joint_tool0_tf.py`. Re-run that exporter after\n"
        "the CAD male-joint OCF or tool0 frame changes.\n\n"
        "All translations are stored in millimeters.\n\n"
        "`MALE_JOINT_OCF_TO_TOOL0[joint_type][arm_side]` is a 4x4 that takes the\n"
        "male-joint local frame (OCF) to the corresponding arm's tool0 frame:\n\n"
        "    tool0_world = male_ocf_world @ MALE_JOINT_OCF_TO_TOOL0[joint_type][arm_side]\n\n"
        "`arm_side` is \"left\" or \"right\" (the two Husky arms carry different\n"
        "physical tools, so the transform differs per side).\n"
        '"""\n\n'
    )

    if not entries:
        body = "MALE_JOINT_OCF_TO_TOOL0 = {}\n"
    else:
        lines = ["MALE_JOINT_OCF_TO_TOOL0 = {"]
        for joint_type in sorted(entries.keys()):
            per_side = entries[joint_type]
            lines.append(f'    "{joint_type}": {{')
            for side in ARM_SIDES:
                if side not in per_side:
                    continue
                lines.append(f'        "{side}": (')
                for row in np.asarray(per_side[side], dtype=float):
                    lines.append(
                        "            (" + ", ".join(f"{float(v):.9g}" for v in row) + "),"
                    )
                lines.append("        ),")
            lines.append("    },")
        lines.append("}\n")
        body = "\n".join(lines)

    with open(path, "w", encoding="utf-8") as stream:
        stream.write(header + body)


def _prompt_joint_type() -> str | None:
    value = rs.GetString("Joint type key", DEFAULT_JOINT_TYPE)
    if value is None:
        return None
    value = value.strip()
    if not value:
        return None
    return value


def _prompt_arm_side() -> str | None:
    value = rs.GetString("Arm side", "left", list(ARM_SIDES))
    if value is None:
        return None
    value = value.strip().lower()
    if value not in ARM_SIDES:
        rs.MessageBox(
            f"Arm side must be one of {ARM_SIDES}.", 0, "Export Male-Joint -> tool0 TF"
        )
        return None
    return value


def main() -> None:
    importlib.reload(_generated_ik)

    joint_type = _prompt_joint_type()
    if joint_type is None:
        print("RSExportJointTool0TF: Cancelled.")
        return

    arm_side = _prompt_arm_side()
    if arm_side is None:
        print("RSExportJointTool0TF: Cancelled.")
        return

    scale_to_mm = doc_unit_scale_to_mm()

    male_group = resolve_frame_group(
        f"Select the baked male-joint frame group for {joint_type} / {arm_side} arm"
    )
    if male_group is None:
        print("RSExportJointTool0TF: Cancelled.")
        return

    tool0_group = resolve_frame_group(
        f"Select the baked tool0 frame group for {joint_type} / {arm_side} arm"
    )
    if tool0_group is None:
        print("RSExportJointTool0TF: Cancelled.")
        return

    try:
        male_frame, male_label = reconstruct_frame(male_group[1], scale_to_mm)
        tool0_frame, tool0_label = reconstruct_frame(tool0_group[1], scale_to_mm)
    except ValueError as exc:
        rs.MessageBox(str(exc), 0, "Export Male-Joint -> tool0 TF")
        return

    tf = invert_transform(male_frame) @ tool0_frame

    # Load existing entries and reject the legacy flat schema with guidance.
    raw = getattr(_generated_ik, "MALE_JOINT_OCF_TO_TOOL0", {}) or {}
    existing: dict[str, dict[str, np.ndarray]] = {}
    for key, value in raw.items():
        if not isinstance(value, dict):
            raise RuntimeError(
                f"config_generated_ik.py entry '{key}' uses the legacy flat schema "
                "(single matrix per joint_type). Delete it and re-run "
                "RSExportJointTool0TF for both left and right arms."
            )
        existing[str(key)] = {
            str(s): np.asarray(v, dtype=float) for s, v in value.items()
        }

    existing.setdefault(joint_type, {})[arm_side] = tf

    output_path = os.path.join(SCRIPT_DIR, "core", "config_generated_ik.py")
    _write_generated_ik(output_path, existing)

    translation = tf[:3, 3]
    print(f"RSExportJointTool0TF: '{joint_type}' / '{arm_side}' written to {output_path}")
    print(
        f"  male group='{male_label}', tool0 group='{tool0_label}', "
        f"translation (mm) = [{translation[0]:.3f}, {translation[1]:.3f}, {translation[2]:.3f}]"
    )
    missing_sides = [s for s in ARM_SIDES if s not in existing.get(joint_type, {})]
    if missing_sides:
        print(
            f"  Note: '{joint_type}' still missing arm side(s): {missing_sides}. "
            "Re-run this script for the missing arm(s) before using RSIKKeyframe."
        )


if __name__ == "__main__":
    main()
